version: '3.3'
services:
  serverstatus:
    network_mode: host
    restart: unless-stopped
    container_name: serverstatusclient
    environment:
      - USER=`name`
      - PASSWORD=`password`
      - PORT=`port`
      - SERVER=`ip`
    image: 'serverstatus:client'
